final Map<String, String> enUs = {
  "app_title": "Tourly Tour",

  /// Splash
  "tourly_tours": "Tourly Tours",

  /// Onboarding
  "drive_your_bangkok": "Drive Your Bangkok Adventure",
  "whispers_of_ancient":
      "Whispers of ancient palaces, secrets in buzzing marketplaces, stories in every smile.",
  "explore_thailand": "Explore Thailand With Us",
  "freedom_for_one":
      "Freedom for One, Spark for Two: Thailand beckons, solo or side-by-side. Experience its vibrant charm at your own pace. Whether you're a solo seeker of hidden alleys nand sunset swims .",
  "let_s_get_start": "Let’s Get Start",

  ///signin
  "login": "Login",
  "new_member": "New member ?",
  "remember_me": "Remember me",
  "forget_password?": "Forget password?",

  ///signup
  "create_account": "Create Account",
  "you_need_to_accept_terms": "You need to accept terms & condition.",
  "i_read_and_agree": "I read and agree to ",
  "terms_condition": "Terms & condition ",

  ///ForgetPasswordScreen
  "forget_password": "Forget Password",
  "reset_password": "Reset Password",
  "please_enter_your_new_password": "Please enter your new password",

  /// OTP Verication Screen
  "enter_otp": "Enter OTP",
  "didn_t_received": "Didn’t received any code ?",
  "we_will_send_you":
      "We will send you a code please check and \nenter the code",
  "re_send_code": "Re-send code",
  "submit_code": "Submit code",

  /// Dashboard
  "whispers_of_ancient2":
      "Whispers of ancient places , secrets in buzzing marketplaces stories in every smile",

  "drive_your_bangkok2": "Drive Your Bangkok\n",
  "adventure": "Adventure",

  //Featured Packges

  "featured_packges": "Featured Packges",

  ///Booking
  "selected_package": "Selected Package",
  "package_options": "Package Options",
  "check_availability": "Check Availability",
  "how_many_of_you": "How many of you are going?\r",
  "number_of_people": "Number of People",
  "ancient_modern": "Ancient & Modern Bangkok Tour (Package 2)",
  "who_should_we_get": "Who should we get in touch for booking updates?",
  "full_name": "Full Name",
  "email_address": "Email Address",
  "mobile_number": "Mobile Number",
  "hotel_name": "Hotel Name",
  "hotel_address": "Hotel Address",
  "hotel_room_number": "Hotel Room Number",
  "guest": "Guest",
  "summary": "Summary",
  "edit_package_options": "Edit package Options",
  "booking": "Booking",
  "pay_tourly_tours": "Pay Tourly Tours",
  "card_information": "Card Information",
  "cardholder_name": "Cardholder Name",
  "country_of_origin": "Country Of Origin",
  "pay_now": "Pay now",
  "power_by": "Power by ",
  "terms_privacy": "Terms   Privacy",

  /// Common
  "rating": "Rating",
  "best_recomendation": "Best Recomendation Tour",
  "continue": "Continue",
  "or": "or ",
  "about": "About",
  "review": "Review",
  "photo": "Photo",
  "video": "Video",
  "remove": "Remove",
  "book_now": "Book Now",
  "bucket_list": "Bucket List",
  "username": "Username",
  "email": "Email",
  "password": "Password",
  "confirm_password": "Confirm password",
  "phone_number": "Phone Number",
  "processing": "Processing",
  "register_now": "Register now",
  "send_code": "Send Code",
  "sending": "Sending",
  "view_details": "View Details",
  "read_more": "Read more",
  "see_more": "See more",
  "see_less": "See less",
  "standard_price": "Standard Price",
  "locations": "Locations",
  "hours": "Hours",
  "usd": "USD",
  "savings": "Savings",
  "compare_packages": "Compare Packages",
  "view_profile": "View Profile",
  "special_deals": "Special Deals",
  "discover": "Discover",
  "eng_us": "Eng-Us",
  "blog": "Blog",
  "wishlist": "Wishlist",
  "contact_us": "Contact Us",
  "sign_up": "Sign Up",
  "profile": "Profile",
  "peolpe": "Peolpe",
  "where": "Where",
  "completed": "Completed",
  "date": "Date",
  "tour_details": "Tour Details",
  "enter_your_review": "Enter your review",
  "view_booking_details": "View Booking Details",
  "blogs": "Blogs",
  "search_destination": "Search Destination",
  "search_tour": "Search Tour",
  "when": "When",
  "select_dates": "Select Dates",
  "update": "Update",
  "phone": "Phone",
  "update_profile": "Update Profile",
  "what_to_expect": "What to Expect",
  "itinerary": "Itinerary",
  "helpful": "Helpful",
  "seamless_experience": "Seamless Experience",
  "hospitality": "Hospitality",
  "value_for_money": "Value for money",
  "impressiveness": "Impressiveness",
  "package_selection": "Package Selection",
  "other_information": "Other Information",
  "payment": "Payment",
  "person": "Person",
  "try_again": "Try Again",
  'name': "Name",
  "passport": "Passport",
  "date_of_birth": "Date of birth",
  "cancel": "Cancel",
  "confirm": "Confirm",
  "print": "Print",
  "share": "Share",
  "share_your_opinion": "Share Your Opinion",
  "tour": "Tour",
  "tours": "Tours",
  "tour_history": "Tour History",
  "submit_review": "Submit Review",
  "skip": "Skip",
  "submit_your_last_experience_review": "Submit your last tour experience.",
  "booking_confirmation": "Booking Confirmation",
  "your_booking_reference_number_is": "Your booking reference number is",
  "booking_date": "Booking Date",
  "paid_on": "Paid on",
  "share_or_print_your_booking_details": "Share or print your booking details",
  "cancellation_policy": "Cancellation Policy",
  "free_cancellation": "Free cancellation",
  "contact": "Contact ",
  "up_to_24_hours_before_the_exprience_starts":
      " up to 24 hours before the exprience starts (local time)",

  "whatsapp": "WhatsApp",
  "instagram": "Instagram",
  "twitter": "Twitter",
  "wechat": "WeChat",
  "viber": "Viber",
  "threads": "Threads",
  "line": "Line",
  "edit": "Edit",
  "guests_information": "Guests Information",
  "passport_no": "Passport No.",
  "locations_for": " Locations for ",
  "people": " People ",
  "auth_session_missing": "Auth session missing",
  "401_unauthorized": "401 Unauthorized",
  //
  "please_enter_your_email_or_phone":
      "Please enter your email or phone number\nto receive the code",
  "please_select_a_date": "Please select a date.",
  "the_total_number_of_guests_cannot_be_less_than_or_equal_to_zero":
      "The total number of guests cannot be less than or equal to zero.",
  'please_enter_your_name': 'Please enter your name',
  'invalid_username_format': 'Invalid username format',
  'please_enter_your_email': 'Please enter your email',
  'invalid_email_format': 'Invalid email format',
  'please_enter_your_password': 'Please enter your password',
  'password_must_contain_the_following':
      'Password must contain the following:\nAt least one uppercase letter.\nAt least one lowercase letter.\nAt least one digit.\nAt least one special character.\nAt least 8 characters long.',
  'please_re_enter_your_password_for_confirmation':
      'Please re-enter your password for confirmation',
  'passwords_do_not_match': 'Passwords do not match',
  'please_enter_the_code_sent_to_your_email':
      'Please enter the code sent to your email',
  'invalid_otp_format': 'Invalid OTP format',
  'please_enter_your_phone': 'Please enter your phone number',
  'invalid_phone_format': 'Invalid phone number format',
  'please_enter_your_full_name': 'Please enter your full name',
  'invalid_full_name_format': 'Invalid full name format',
  'please_enter_your_email_address': 'Please enter your email address',
  'invalid_email_address_format': 'Invalid email address format',
  'please_enter_your_mobile_number': 'Please enter your mobile number',
  'invalid_mobile_number_format': 'Invalid mobile number format',
  'please_enter_the_hotel_name': 'Please enter the hotel name',
  'invalid_hotel_name_format': 'Invalid hotel name format',
  'please_enter_the_hotel_address': 'Please enter the hotel address',
  'invalid_hotel_address_format': 'Invalid hotel address format',
  'please_enter_the_hotel_room_number': 'Please enter the hotel room number',
  'invalid_hotel_room_number_format': 'Invalid hotel room number format',
  'please_enter_the_guest_name': 'Please enter the guest name',
  'invalid_guest_name_format': 'Invalid guest name format',
  'please_enter_the_guest_passport': 'Please enter the guest passport',
  'invalid_guest_passport_format': 'Invalid guest passport format',
  'please_enter_the_guest_date_of_birth':
      'Please enter the guest date of birth.\ni.e YYYY-MM-DD',
  'invalid_guest_date_of_birth_format':
      'Invalid guest date of birth format.\ni.e YYYY-MM-DD',

  /// Network Error String
  "network_err": "Network Error",
  "no_records_found": "No records found.",
  "something_went_wrong": "Something Went Wrong!",
  "no_internet_connection": "No internet connection",
};
